laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'site.home', 'uses' => 'HomeController@index']);
Route::get('about', ['as' => 'site.about', 'uses' => 'AboutController@index']);
Route::get('imprensa', ['as' => 'site.imprensa', 'uses' => 'ImprensaController@index']);
Route::get('publicacoes', ['as' => 'site.publicacoes', 'uses' => 'PublicacoesController@index']);
Route::get('acao-social', ['as' => 'site.acaosocial', 'uses' => 'AcaoSocialController@index']);
Route::get('juridico', ['as' => 'site.juridico', 'uses' => 'JuridicoController@index']);
Route::get('parcerias', ['as' => 'site.parcerias', 'uses' => 'ParceriasController@index']);
Route::get('licenciamento', ['as' => 'site.licenciamento', 'uses' => 'LicenciamentoController@index']);
Route::get('contato', ['as' => 'site.contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'site.contato.enviar', 'uses' => 'ContatoController@enviar']);
Route::get('destaques', ['as' => 'site.destaques', 'uses' => 'DestaquesController@index']);

Route::get('portfolio/entrada/{slug?}', ['as' => 'site.portfolio.entrada', 'uses' => 'PortfolioController@entrada']);
Route::get('portfolio/detalhe/{slug?}', ['as' => 'site.portfolio.detalhe', 'uses' => 'PortfolioController@detalhe']);
Route::get('portfolio/release/{slug?}', ['as' => 'site.portfolio.release', 'uses' => 'PortfolioController@release']);

Route::post('mosaico/novo-item', function(Illuminate\Http\Request $request){

	$tipo = $request->tipo;
	$ids_atuais = $request->ids_atuais;

	if($tipo == 'personalidade'){

		$item = App\Models\PortfolioPersonalidades::comThumb()
																							->where('publicar', 1)
																							->aleatorio()
																							->whereNotIn('id', $ids_atuais)
																							->whereHas('categoria', function($query){
																								$query->where('publicar', 1);
																							})
																							->first()
																							->toArray();

	}elseif($tipo == 'categoria'){

		$omitir = [9, 11];

		$item = App\Models\PortfolioCategorias::ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}elseif($tipo == 'subcategoria'){

		$omitir = [13, 18, 22];

		$item = App\Models\PortfolioSubcategorias::with('categoria')->ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}

	return $item;
});

// Route::get('cut', function(){
// 	$r = App\Models\PortfolioPersonalidades::all();
// 	foreach($r as $port){
//
// 		$img = $port->imagem_entrada;
// 		$port->thumb_home = $img;
// 		$port->save();
//
// 		echo $img.' redimensionado<br>';
//
// 	}
// });
//*******************************************************************************************//
//*******************************************************************************************//
//*******************************************************************************************//


// Tela de Login do painel
Route::get('painel/login', ['as' => 'painel.login', 'uses' => 'Painel\HomeController@login']);

// Efetuar Login via POST
Route::post('painel/login', ['as' => 'painel.auth', 'uses' => 'Auth\AuthController@postLogin']);

// Logout do Painel
Route::get('painel/logout', ['as' => 'painel.off', 'uses' => 'Auth\AuthController@getLogout']);

Route::post('getSubcategorias', ['as' => 'get.subcategorias', function(Illuminate\Http\Request $request){

	$categoria = App\Models\PortfolioCategorias::find($request->input('cat_id'));

	if($categoria)
		return $categoria->subcategorias;
	else
		return [];
}]);


// Página principal do Painel
Route::group([
		'middleware' => 'auth',
		'namespace' => 'Painel',
		'prefix' => 'painel'
	], function () {

		Route::get('/', ['as' => 'painel.home', 'uses' => 'HomeController@index']);
		Route::post('imagens/upload', ['as' => 'imagens.upload', 'uses' => 'ImagensController@upload']);
		Route::post('imagens/uploadParalaxe', ['as' => 'imagens.upload-paralaxe', 'uses' => 'ImagensController@uploadParalaxe']);
		Route::post('idiomas/adicionar', 'PortfolioController@postAdicionarIdioma');

		Route::post('ajax/gravaOrdem', function(Illuminate\Http\Request $request){
      $itens = $request->input('data');
      $tabela = $request->input('tabela');
      for ($i = 0; $i < count($itens); $i++)
       DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
    });

		Route::resource('usuarios', 'UsuariosController', ['except' => ['show']]);

		Route::resource('about', 'AboutController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('imprensa', 'ImprensaController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('juridico', 'JuridicoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('publicacoes', 'PublicacoesController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('acaosocial', 'AcaoSocialController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('parcerias', 'ParceriasController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('licenciamento', 'LicenciamentoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('contato', 'ContatoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('portfolio', 'PortfolioController', ['except' => ['show']]);

		Route::resource('idiomas', 'IdiomasController', ['except' => ['show']]);

		Route::resource('marca', 'MarcaController', ['except' => ['show']]);
    Route::resource('banners', 'BannersController', ['except' => ['show']]);
    
    Route::resource('destaques', 'DestaquesController', ['only' => ['index', 'edit', 'update']]);
	}
);


/*
Route::get('fix-83jf3453165f413q1f', function(){
	$registros = \App\Models\PortfolioParalaxe::all();
	foreach($registros as $registro){
		for ($i=1; $i <= 5; $i++) {

			$titulo = "imagem_{$i}";
			$img = $registro->{$titulo};

			$diretorios = [
				'assets/img/portfolio/paralaxe/originais/',
				'assets/img/portfolio/paralaxe/redimensionadas/horizontais/',
				'assets/img/portfolio/paralaxe/redimensionadas/verticais/',
				'assets/img/portfolio/paralaxe/thumbs/'
			];

			foreach($diretorios as $dir){
				if($img != '' && $img != '.' && $img != '..' && $img != '/' && !file_exists(public_path($dir.$img))){
					echo "-- NAO encontrado: {$dir}{$img} <br>";

					$outros_tipos = ['jpg', 'jpeg', 'bmp', 'tif', 'gif'];
					foreach($outros_tipos as $tipo){
						$novo_tipo = str_replace('png', $tipo, $img);
						if(file_exists(public_path($dir.$novo_tipo))){
							echo "mas existe {$tipo}<br>";
							//rename(public_path($dir.$novo_tipo), public_path($dir.$img));
						}
					}
					echo '<br>';
				}
			}

		}
	}
});
*/

laravel/app/Http/Controllers/Painel/AboutController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\About;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = About::all();

        return view('painel.about.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.about.edit')->with('registro', About::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = About::find($id);

        $object->texto = $request->input('texto');

        $imagem = Thumbs::make('imagem', 900, 900, 'about/');
        if($imagem) $object->imagem = $imagem;

        $object->instagram = $request->input('instagram');
        $object->twitter   = $request->input('twitter');
        $object->facebook  = $request->input('facebook');
        $object->tumblr    = $request->input('tumblr');
        $object->linkedin  = $request->input('linkedin');
        $object->pinterest = $request->input('pinterest');
        $object->youtube   = $request->input('youtube');
        $object->periscope = $request->input('periscope');
        $object->vimeo     = $request->input('vimeo');
        $object->googleplus= $request->input('googleplus');
        $object->wordpress = $request->input('wordpress');
        $object->snapchat  = $request->input('snapchat');

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.about.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/AcaoSocialController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\AcaoSocial;
use App\Models\AcaoSocialImagens;

class AcaoSocialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = AcaoSocial::all();

        return view('painel.acaosocial.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.acaosocial.edit')->with('registro', AcaoSocial::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = AcaoSocial::find($id);

        $object->texto = $request->input('texto');

        try {

            $object->save();

            $this->updateImagens($request, $id);

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.acaosocial.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

    /**
     * Update the images od the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return void
     */

    private function updateImagens(Request $request, $id)
    {
        AcaoSocialImagens::where('acao_social_id', '=', $id)->delete();

        $imagens = $request->get('imagem');

        if($imagens && is_array($imagens)){
            foreach ($imagens as $key => $value) {
                $obj = new AcaoSocialImagens;
                $obj->acao_social_id = $id;
                $obj->imagem = $value;
                $obj->ordem = $key;
                $obj->save();
            }
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Libs\Thumbs;

class BannersController extends Controller
{

  protected $pathImagens = 'banners/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Banner::ordenado()->get();

      return view('painel.banners.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.banners.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'imagem' => 'required|image'
    	]);

      $object = new Banner;

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.banners.edit')->with('registro', Banner::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'imagem' => 'sometimes|image'
    	]);

      $object = Banner::find($id);

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Banner::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.banners.index');
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\Contato;

class ContatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = Contato::all();

        return view('painel.contato.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.contato.edit')->with('registro', Contato::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = Contato::find($id);

        $object->fill($request->except('_method', '_token'));

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.contato.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use View;

class HomeController extends Controller {

    public function index()
	{
		return View::make('painel.home.index');
	}

	public function login()
	{
		return View::make('painel.login.index');
	}

}

laravel/app/Http/Controllers/Painel/ImprensaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\Imprensa;

class ImprensaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = Imprensa::all();

        return view('painel.imprensa.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.imprensa.edit')->with('registro', Imprensa::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = Imprensa::find($id);

        $object->texto = $request->input('texto');

        $imagem = Thumbs::make('imagem', 900, 900, 'imprensa/');
        if($imagem) $object->imagem = $imagem;

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.imprensa.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/resources/views/painel/portfolio/create.blade.php
@extends('painel.template.index')

@section('conteudo')

    <div class="container-fluid padded-bottom">
    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

		      	<h2>
		        	Portfolio <small>Adicionar Personalidade</small>
		        </h2>

		        <hr>

		        @include('painel.template.mensagens')

				<form action="{{ URL::route('painel.portfolio.store') }}" method="post" enctype="multipart/form-data">

					{!! csrf_field() !!}

					<div class="form-group">
						<label for="inputCategoria">Categoria</label>
						<select name="portfolio_categorias_id" id="inputCategoria" class="form-control" required>
							<option value="">Selecione uma Categoria</option>
							@foreach($listaCategorias as $categoria)
								<option value="{{ $categoria->id }}" @if(old('portfolio_categorias_id') == $categoria->id) selected @endif >{{ $categoria->titulo }}</option>
							@endforeach
						</select>
					</div>

					<div class="form-group" id='contemSelectSubcategorias'>
						<label for="inputSubcategoria">Subcategoria</label>
						<select name="portfolio_subcategorias_id" id="inputSubcategoria" class="form-control">
							<option value="">Selecione uma Subcategoria</option>
						</select>
						<input type="hidden" id="portfolio_subcategorias_id_selecionado" value="{{ old('portfolio_subcategorias_id') }}">
					</div>

			    	<div class="form-group">
						<label for="inputNome">Nome</label>
						<input type="text" class="form-control" id="inputNome" name="nome"  value="{{ old('nome') }}" required>
					</div>

					<div class="form-group">
						<label for="inputCorNome">Cor do Nome na página do Portfolio</label>
						<select name="cor_nome" id="inputCorNome" required class='form-control'>
							<option value="FFF" @if(old('cor_nome') == 'FFF') selected @endif >BRANCO</option>
							<option value="000" @if(old('cor_nome') == '000') selected @endif >PRETO</option>
						</select>
					</div>

					<div class="well">
						<div class="form-group">
							<label for="inputImagem">Imagem de Entrada</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem_entrada" required>
						</div>
					</div>

          <div class="well">
						<div class="form-group">
							<label for="inputThumbHome">Thumbnail para a Home</label>
							<input type="file" class="form-control" id="inputThumbHome" name="thumb_home" required>
						</div>
					</div>

					<div class="well">
						<div class="form-group">
							<label for="inputRelease">Release</label>
							<input type="file" class="form-control" id="inputRelease" name="arquivo_release">
						</div>
					</div>

					<div class="form-group">
						<label for="inputLinkSite">Link para o site</label>
						<input type="text" class="form-control" id="inputLinkSite" name="link_site"  value="{{ old('link_site') }}">
					</div>

          <div class="well">
            <div class="row">
              <label class="col-sm-6">
                <input type="radio" name="publicar" value="publicar" required @if(old('publicar') == 'publicar') checked @endif > Publicar
              </label>
              <label class="col-sm-6">
                <input type="radio" name="publicar" value="rascunho" @if(old('publicar') == 'rascunho') checked @endif > Salvar como rascunho
              </label>
            </div>
          </div>

					<hr>

					<h3>Módulos</h3>

					<div class="panel panel-default">
						<div class="panel-body">
					    	Clique nos módulos para inserí-los no cadastro.
					  	</div>
					</div>

					@include('painel.portfolio.paralaxe')

					@include('painel.portfolio.fotos')

					@include('painel.portfolio.personagens', compact('registro'))

					@include('painel.portfolio.capas')

					@include('painel.portfolio.publicidade')

					@include('painel.portfolio.desfiles')

					@include('painel.portfolio.videos')

					@include('painel.portfolio.acaosocial')

					@include('painel.portfolio.editorialdemoda')

					@include('painel.portfolio.personalstylist')

					@include('painel.portfolio.redessociais')

					@include('painel.portfolio.palestras')

					@include('painel.portfolio.consultoriamoda')

					@include('painel.portfolio.publicacoes')

					@include('painel.portfolio.extras')

					@include('painel.portfolio.redcarpet')

					@include('painel.portfolio.espetaculos')

					@include('painel.portfolio.workshops')

					@include('painel.portfolio.creditos')

          @include('painel.portfolio.idiomas')

          @include('painel.portfolio.premios')

					<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

					<a href="{{ URL::route('painel.portfolio.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

				</form>
			</div>
		</div>
    </div>

@endsection

laravel/resources/views/painel/portfolio/edit.blade.php
@extends('painel.template.index')

@section('conteudo')

    <div class="container-fluid padded-bottom">
    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

		      	<h2>
		        	Portfolio <small>Editar Personalidade</small>
		        </h2>

		        <hr>

		        @include('painel.template.mensagens')

				<form action="{{ URL::route('painel.portfolio.update', $registro->id) }}" method="post" enctype="multipart/form-data">

					<input type="hidden" name="_method" value="PUT">

					{!! csrf_field() !!}

					<div class="form-group">
						<label for="inputCategoria">Categoria</label>
						<select name="portfolio_categorias_id" id="inputCategoria" class="form-control" required>
							<option value="">Selecione uma Categoria</option>
							@foreach($listaCategorias as $categoria)
								<option value="{{ $categoria->id }}" @if($registro->portfolio_categorias_id == $categoria->id) selected @endif >{{ $categoria->titulo }}</option>
							@endforeach
						</select>
					</div>

					<div class="form-group" id='contemSelectSubcategorias'>
						<label for="inputSubcategoria">Subcategoria</label>
						<select name="portfolio_subcategorias_id" id="inputSubcategoria" class="form-control">
							<option value="">Selecione uma Subcategoria</option>
						</select>
						<input type="hidden" id="portfolio_subcategorias_id_selecionado" value="{{ $registro->portfolio_subcategorias_id }}">
					</div>

			    	<div class="form-group">
						<label for="inputNome">Nome</label>
						<input type="text" class="form-control" id="inputNome" name="nome"  value="{{ $registro->nome }}" required>
					</div>

					<div class="form-group">
						<label for="inputCorNome">Cor do Nome na página do Portfolio</label>
						<select name="cor_nome" id="inputCorNome" required class='form-control'>
							<option value="FFF" @if($registro->cor_nome == 'FFF') selected @endif >BRANCO</option>
							<option value="000" @if($registro->cor_nome == '000') selected @endif >PRETO</option>
						</select>
					</div>

					<div class="well">
						<div class="form-group">
							@if($registro->imagem_entrada)
								Imagem Atual<br>
								<img src="assets/img/portfolio/entrada/{{$registro->imagem_entrada}}" style='max-width:100%;'><hr>
							@endif
							<label for="inputImagem">Imagem de Entrada</label>
							<input type="file" class="form-control" id="inputImagem" name="imagem_entrada">
						</div>
					</div>

          <div class="well">
						<div class="form-group">
							@if($registro->thumb_home)
								Thumbnail Atual<br>
								<img src="assets/img/portfolio/thumbs-home/{{$registro->thumb_home}}" style='max-width: 200px;'><hr>
                <hr>
                <label><input type="checkbox" name="remover_thumb_home" value="1"> Remover imagem atual</label>
							@endif
              <hr>
							<label for="inputThumbHome">Nova Thumbnail para a Home</label>
							<input type="file" class="form-control" id="inputThumbHome" name="thumb_home">
						</div>
					</div>

					<div class="well">
						<div class="form-group">
							@if($registro->arquivo_release)
								Release Atual :
								<a href="assets/releases/{{ $registro->arquivo_release }}" class='btn btn-sm btn-default' target='_blank'>{{ $registro->arquivo_release }}</a><hr>
							@endif
							<label for="inputRelease">Release</label>
							<input type="file" class="form-control" id="inputRelease" name="arquivo_release">
						</div>
					</div>

					<div class="form-group">
						<label for="inputLinkSite">Link para o site</label>
						<input type="text" class="form-control" id="inputLinkSite" name="link_site"  value="{{ $registro->link_site }}">
					</div>

          <div class="well">
            <div class="row">
              <label class="col-sm-6">
                <input type="radio" name="publicar" value="publicar" required @if($registro->publicar == 1) checked @endif > Publicar
              </label>
              <label class="col-sm-6">
                <input type="radio" name="publicar" value="rascunho" @if($registro->publicar == 0) checked @endif > Salvar como rascunho
              </label>
            </div>
          </div>

					<hr>

					<h3>Módulos</h3>

					<div class="panel panel-default">
						<div class="panel-body">
					    	Clique nos módulos para inserí-los no cadastro.
					  	</div>
					</div>

					@include('painel.portfolio.paralaxe', compact('registro'))

					@include('painel.portfolio.fotos', compact('registro'))

					@include('painel.portfolio.personagens', compact('registro'))

					@include('painel.portfolio.capas', compact('registro'))

					@include('painel.portfolio.publicidade', compact('registro'))

					@include('painel.portfolio.desfiles', compact('registro'))

					@include('painel.portfolio.videos', compact('registro'))

					@include('painel.portfolio.acaosocial', compact('registro'))

					@include('painel.portfolio.editorialdemoda', compact('registro'))

					@include('painel.portfolio.personalstylist', compact('registro'))

					@include('painel.portfolio.redessociais', compact('registro'))

					@include('painel.portfolio.palestras', compact('registro'))

					@include('painel.portfolio.consultoriamoda', compact('registro'))

					@include('painel.portfolio.publicacoes', compact('registro'))

					@include('painel.portfolio.extras', compact('registro'))

					@include('painel.portfolio.redcarpet', compact('registro'))

					@include('painel.portfolio.espetaculos', compact('registro'))

					@include('painel.portfolio.workshops', compact('registro'))

					@include('painel.portfolio.creditos', compact('registro'))

          @include('painel.portfolio.idiomas', compact('registro'))

          @include('painel.portfolio.premios', compact('registro'))

					<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

					<a href="{{ URL::route('painel.portfolio.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

				</form>
			</div>
		</div>
    </div>

@endsection