laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'site.home', 'uses' => 'HomeController@index']);
Route::get('about', ['as' => 'site.about', 'uses' => 'AboutController@index']);
Route::get('imprensa', ['as' => 'site.imprensa', 'uses' => 'ImprensaController@index']);
Route::get('publicacoes', ['as' => 'site.publicacoes', 'uses' => 'PublicacoesController@index']);
Route::get('acao-social', ['as' => 'site.acaosocial', 'uses' => 'AcaoSocialController@index']);
Route::get('juridico', ['as' => 'site.juridico', 'uses' => 'JuridicoController@index']);
Route::get('parcerias', ['as' => 'site.parcerias', 'uses' => 'ParceriasController@index']);
Route::get('licenciamento', ['as' => 'site.licenciamento', 'uses' => 'LicenciamentoController@index']);
Route::get('contato', ['as' => 'site.contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'site.contato.enviar', 'uses' => 'ContatoController@enviar']);
Route::get('destaques', ['as' => 'site.destaques', 'uses' => 'DestaquesController@index']);

Route::get('portfolio/entrada/{slug?}', ['as' => 'site.portfolio.entrada', 'uses' => 'PortfolioController@entrada']);
Route::get('portfolio/detalhe/{slug?}', ['as' => 'site.portfolio.detalhe', 'uses' => 'PortfolioController@detalhe']);
Route::get('portfolio/release/{slug?}', ['as' => 'site.portfolio.release', 'uses' => 'PortfolioController@release']);

Route::post('mosaico/novo-item', function(Illuminate\Http\Request $request){

	$tipo = $request->tipo;
	$ids_atuais = $request->ids_atuais;

	if($tipo == 'personalidade'){

		$item = App\Models\PortfolioPersonalidades::comThumb()
																							->where('publicar', 1)
																							->aleatorio()
																							->whereNotIn('id', $ids_atuais)
																							->whereHas('categoria', function($query){
																								$query->where('publicar', 1);
																							})
																							->first()
																							->toArray();

	}elseif($tipo == 'categoria'){

		$omitir = [9, 11];

		$item = App\Models\PortfolioCategorias::ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}elseif($tipo == 'subcategoria'){

		$omitir = [13, 18, 22];

		$item = App\Models\PortfolioSubcategorias::with('categoria')->ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}

	return $item;
});

// Route::get('cut', function(){
// 	$r = App\Models\PortfolioPersonalidades::all();
// 	foreach($r as $port){
//
// 		$img = $port->imagem_entrada;
// 		$port->thumb_home = $img;
// 		$port->save();
//
// 		echo $img.' redimensionado<br>';
//
// 	}
// });
//*******************************************************************************************//
//*******************************************************************************************//
//*******************************************************************************************//


// Tela de Login do painel
Route::get('painel/login', ['as' => 'painel.login', 'uses' => 'Painel\HomeController@login']);

// Efetuar Login via POST
Route::post('painel/login', ['as' => 'painel.auth', 'uses' => 'Auth\AuthController@postLogin']);

// Logout do Painel
Route::get('painel/logout', ['as' => 'painel.off', 'uses' => 'Auth\AuthController@getLogout']);

Route::post('getSubcategorias', ['as' => 'get.subcategorias', function(Illuminate\Http\Request $request){

	$categoria = App\Models\PortfolioCategorias::find($request->input('cat_id'));

	if($categoria)
		return $categoria->subcategorias;
	else
		return [];
}]);


// Página principal do Painel
Route::group([
		'middleware' => 'auth',
		'namespace' => 'Painel',
		'prefix' => 'painel'
	], function () {

		Route::get('/', ['as' => 'painel.home', 'uses' => 'HomeController@index']);
		Route::post('imagens/upload', ['as' => 'imagens.upload', 'uses' => 'ImagensController@upload']);
		Route::post('imagens/uploadParalaxe', ['as' => 'imagens.upload-paralaxe', 'uses' => 'ImagensController@uploadParalaxe']);
		Route::post('idiomas/adicionar', 'PortfolioController@postAdicionarIdioma');

		Route::post('ajax/gravaOrdem', function(Illuminate\Http\Request $request){
      $itens = $request->input('data');
      $tabela = $request->input('tabela');
      for ($i = 0; $i < count($itens); $i++)
       DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
    });

		Route::resource('usuarios', 'UsuariosController', ['except' => ['show']]);

		Route::resource('about', 'AboutController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('imprensa', 'ImprensaController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('juridico', 'JuridicoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('publicacoes', 'PublicacoesController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('acaosocial', 'AcaoSocialController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('parcerias', 'ParceriasController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('licenciamento', 'LicenciamentoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('contato', 'ContatoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('portfolio', 'PortfolioController', ['except' => ['show']]);

		Route::resource('idiomas', 'IdiomasController', ['except' => ['show']]);

		Route::resource('marca', 'MarcaController', ['except' => ['show']]);
    Route::resource('banners', 'BannersController', ['except' => ['show']]);
    
    Route::resource('destaques', 'DestaquesController', ['only' => ['index', 'edit', 'update']]);
	}
);


/*
Route::get('fix-83jf3453165f413q1f', function(){
	$registros = \App\Models\PortfolioParalaxe::all();
	foreach($registros as $registro){
		for ($i=1; $i <= 5; $i++) {

			$titulo = "imagem_{$i}";
			$img = $registro->{$titulo};

			$diretorios = [
				'assets/img/portfolio/paralaxe/originais/',
				'assets/img/portfolio/paralaxe/redimensionadas/horizontais/',
				'assets/img/portfolio/paralaxe/redimensionadas/verticais/',
				'assets/img/portfolio/paralaxe/thumbs/'
			];

			foreach($diretorios as $dir){
				if($img != '' && $img != '.' && $img != '..' && $img != '/' && !file_exists(public_path($dir.$img))){
					echo "-- NAO encontrado: {$dir}{$img} <br>";

					$outros_tipos = ['jpg', 'jpeg', 'bmp', 'tif', 'gif'];
					foreach($outros_tipos as $tipo){
						$novo_tipo = str_replace('png', $tipo, $img);
						if(file_exists(public_path($dir.$novo_tipo))){
							echo "mas existe {$tipo}<br>";
							//rename(public_path($dir.$novo_tipo), public_path($dir.$img));
						}
					}
					echo '<br>';
				}
			}

		}
	}
});
*/

laravel/app/Models/Destaque.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Destaque extends Model
{

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'destaques';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['id'];

    public function imagens()
    {
        return $this->hasMany('App\Models\DestaquesBanners', 'destaque_id')->orderBy('ordem', 'asc');
    }
}

laravel/app/Http/Controllers/DestaquesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Destaque;
use App\Models\DestaquesBanners;
use App\Libs\Youtube;

class DestaquesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $destaques = Destaque::first();
      $embed1 = new Youtube($destaques->embed_1);
      $embed2 = new Youtube($destaques->embed_2);
      $banners = DestaquesBanners::orderByRaw("RAND()")->get();

      return view('site.destaques.index')->with([
        'destaques' => $destaques,
        'embed1' => $embed1->getEmbed(500),
        'embed2' => $embed2->getEmbed(500),
        'banners' => $banners
      ]);
    }
}

laravel/app/Http/Controllers/Painel/AboutController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\About;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = About::all();

        return view('painel.about.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.about.edit')->with('registro', About::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = About::find($id);

        $object->texto = $request->input('texto');

        $imagem = Thumbs::make('imagem', 900, 900, 'about/');
        if($imagem) $object->imagem = $imagem;

        $object->instagram = $request->input('instagram');
        $object->twitter   = $request->input('twitter');
        $object->facebook  = $request->input('facebook');
        $object->tumblr    = $request->input('tumblr');
        $object->linkedin  = $request->input('linkedin');
        $object->pinterest = $request->input('pinterest');
        $object->youtube   = $request->input('youtube');
        $object->periscope = $request->input('periscope');
        $object->vimeo     = $request->input('vimeo');
        $object->googleplus= $request->input('googleplus');
        $object->wordpress = $request->input('wordpress');
        $object->snapchat  = $request->input('snapchat');

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.about.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/AcaoSocialController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\AcaoSocial;
use App\Models\AcaoSocialImagens;

class AcaoSocialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = AcaoSocial::all();

        return view('painel.acaosocial.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.acaosocial.edit')->with('registro', AcaoSocial::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = AcaoSocial::find($id);

        $object->texto = $request->input('texto');

        try {

            $object->save();

            $this->updateImagens($request, $id);

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.acaosocial.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

    /**
     * Update the images od the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return void
     */

    private function updateImagens(Request $request, $id)
    {
        AcaoSocialImagens::where('acao_social_id', '=', $id)->delete();

        $imagens = $request->get('imagem');

        if($imagens && is_array($imagens)){
            foreach ($imagens as $key => $value) {
                $obj = new AcaoSocialImagens;
                $obj->acao_social_id = $id;
                $obj->imagem = $value;
                $obj->ordem = $key;
                $obj->save();
            }
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Libs\Thumbs;

class BannersController extends Controller
{

  protected $pathImagens = 'banners/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Banner::ordenado()->get();

      return view('painel.banners.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.banners.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'imagem' => 'required|image'
    	]);

      $object = new Banner;

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.banners.edit')->with('registro', Banner::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'imagem' => 'sometimes|image'
    	]);

      $object = Banner::find($id);

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Banner::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.banners.index');
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\Contato;

class ContatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = Contato::all();

        return view('painel.contato.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.contato.edit')->with('registro', Contato::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = Contato::find($id);

        $object->fill($request->except('_method', '_token'));

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.contato.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use View;

class HomeController extends Controller {

    public function index()
	{
		return View::make('painel.home.index');
	}

	public function login()
	{
		return View::make('painel.login.index');
	}

}

laravel/resources/views/painel/destaques/edit.blade.php
@extends('painel.template.index')

@section('conteudo')

  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
        
        <h2>Editar Destaques</h2>

        <hr>

        @include('painel.template.mensagens')

        <form action="{{ URL::route('painel.destaques.update', $registro->id) }}" method="post" enctype="multipart/form-data">
          <input type="hidden" name="_method" value="PUT">
          {!! csrf_field() !!}

          <label for="inputImagem">Destaque 1</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_1)
              <div>
							  <img src="assets/img/destaques/{{$registro->imagem_1}}" class="img-thumbnail">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_1">
					</div>

          <div class="form-group">
						<label for="inputLink1">Link</label>
						<input type="text" class="form-control" id="inputLink1" name="link_1" value="{{ $registro->link_1 }}">
					</div>

          <hr>

          <label for="inputImagem">Destaque 2</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_2)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_2}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_2">
					</div>

          <div class="form-group">
						<label for="inputLink2">Link</label>
						<input type="text" class="form-control" id="inputLink2" name="link_2" value="{{ $registro->link_2 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 3</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_3)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_3}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_3">
					</div>

          <div class="form-group">
						<label for="inputLink3">Link</label>
						<input type="text" class="form-control" id="inputLink3" name="link_3" value="{{ $registro->link_3 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 4</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_4)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_4}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_4">
					</div>

          <div class="form-group">
						<label for="inputLink4">Link</label>
						<input type="text" class="form-control" id="inputLink4" name="link_4" value="{{ $registro->link_4 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 5</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_5)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_5}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_5">
					</div>

          <div class="form-group">
						<label for="inputLink5">Link</label>
						<input type="text" class="form-control" id="inputLink5" name="link_5" value="{{ $registro->link_5 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 6</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_6)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_6}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_6">
					</div>

          <div class="form-group">
						<label for="inputLink6">Link</label>
						<input type="text" class="form-control" id="inputLink6" name="link_6" value="{{ $registro->link_6 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 7</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_7)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_7}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_7">
					</div>

          <div class="form-group">
						<label for="inputLink7">Link</label>
						<input type="text" class="form-control" id="inputLink7" name="link_7" value="{{ $registro->link_7 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 8</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_8)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_8}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_8">
					</div>

          <div class="form-group">
						<label for="inputLink8">Link</label>
						<input type="text" class="form-control" id="inputLink8" name="link_8" value="{{ $registro->link_8 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 9</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_9)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_9}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_9">
					</div>

          <div class="form-group">
						<label for="inputLink9">Link</label>
						<input type="text" class="form-control" id="inputLink9" name="link_9" value="{{ $registro->link_9 }}">
					</div>

          <hr>
          
          <label for="inputImagem">Destaque 10</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_10)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_10}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_10">
					</div>

          <div class="form-group">
						<label for="inputLink10">Link</label>
						<input type="text" class="form-control" id="inputLink10" name="link_10" value="{{ $registro->link_10 }}">
          </div>
          
          <hr>
          
          <label for="inputImagem">Destaque 11</label>

          <div class="form-group">
          <label for="inputImagem">Imagem</label>
						@if($registro->imagem_11)
              <div>
							  <img class="img-thumbnail" src="assets/img/destaques/{{$registro->imagem_11}}">
              </div>
						@endif
						<input type="file" class="form-control" id="inputImagem" name="imagem_11">
					</div>

          <div class="form-group">
						<label for="inputLink10">Link</label>
						<input type="text" class="form-control" id="inputLink10" name="link_11" value="{{ $registro->link_11 }}">
					</div>

          <hr>

          <h2>Destaques em Vídeo</h2>

          <div class="form-group">
						<label for="inputVideo1">Vídeo 1 (URL do youtube)</label><br>
            {!! $video1->getEmbed(600) !!}
						<input type="text" class="form-control" id="inputVideo1" name="embed_1" value="{{ $registro->embed_1 }}">
					</div>
          
          <div class="form-group">
						<label for="inputVideo2">Vídeo 2 (URL do youtube)</label><br>
            {!! $video2->getEmbed(600) !!}
						<input type="text" class="form-control" id="inputVideo2" name="embed_2" value="{{ $registro->embed_2 }}">
          </div>
          
          <hr>

          <h2>Banners</h2>

          <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
              @include('painel.template.imagens-upload', ['registro' => $registro, 'path' => 'banners_destaques', 'hide_ordering' => true])
            </div>
          </div>

          <hr>

          <button type="submit" title="Alterar" class="btn btn-success">Alterar</button>
          <a href="{{ URL::route('painel.destaques.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>
        </form>
      </div>
    </div>
  </div>

@endsection

laravel/resources/views/painel/destaques/index.blade.php
@extends('painel.template.index')

@section('conteudo')
  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        
        <h2>Destaques</h2>

        <hr>
        @include('painel.template.mensagens')
        
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Página</th>
              <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
          </thead>
          <tbody>
          @foreach ($registros as $registro)
            <tr class="tr-row">
              <td>
                <b>DESTAQUES</b>
              </td>
              <td class="crud-actions">
                <a href="{{ URL::route('painel.destaques.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>
              </td>
            </tr>
          @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection