laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'site.home', 'uses' => 'HomeController@index']);
Route::get('about', ['as' => 'site.about', 'uses' => 'AboutController@index']);
Route::get('imprensa', ['as' => 'site.imprensa', 'uses' => 'ImprensaController@index']);
Route::get('publicacoes', ['as' => 'site.publicacoes', 'uses' => 'PublicacoesController@index']);
Route::get('acao-social', ['as' => 'site.acaosocial', 'uses' => 'AcaoSocialController@index']);
Route::get('juridico', ['as' => 'site.juridico', 'uses' => 'JuridicoController@index']);
Route::get('parcerias', ['as' => 'site.parcerias', 'uses' => 'ParceriasController@index']);
Route::get('licenciamento', ['as' => 'site.licenciamento', 'uses' => 'LicenciamentoController@index']);
Route::get('contato', ['as' => 'site.contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'site.contato.enviar', 'uses' => 'ContatoController@enviar']);
Route::get('destaques', ['as' => 'site.destaques', 'uses' => 'DestaquesController@index']);

Route::get('portfolio/entrada/{slug?}', ['as' => 'site.portfolio.entrada', 'uses' => 'PortfolioController@entrada']);
Route::get('portfolio/detalhe/{slug?}', ['as' => 'site.portfolio.detalhe', 'uses' => 'PortfolioController@detalhe']);
Route::get('portfolio/release/{slug?}', ['as' => 'site.portfolio.release', 'uses' => 'PortfolioController@release']);

Route::post('mosaico/novo-item', function(Illuminate\Http\Request $request){

	$tipo = $request->tipo;
	$ids_atuais = $request->ids_atuais;

	if($tipo == 'personalidade'){

		$item = App\Models\PortfolioPersonalidades::comThumb()
																							->where('publicar', 1)
																							->aleatorio()
																							->whereNotIn('id', $ids_atuais)
																							->whereHas('categoria', function($query){
																								$query->where('publicar', 1);
																							})
																							->first()
																							->toArray();

	}elseif($tipo == 'categoria'){

		$omitir = [9, 11];

		$item = App\Models\PortfolioCategorias::ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}elseif($tipo == 'subcategoria'){

		$omitir = [13, 18, 22];

		$item = App\Models\PortfolioSubcategorias::with('categoria')->ordenado()->whereNotIn('id', array_merge($ids_atuais, $omitir))->first()->toArray();

	}

	return $item;
});

// Route::get('cut', function(){
// 	$r = App\Models\PortfolioPersonalidades::all();
// 	foreach($r as $port){
//
// 		$img = $port->imagem_entrada;
// 		$port->thumb_home = $img;
// 		$port->save();
//
// 		echo $img.' redimensionado<br>';
//
// 	}
// });
//*******************************************************************************************//
//*******************************************************************************************//
//*******************************************************************************************//


// Tela de Login do painel
Route::get('painel/login', ['as' => 'painel.login', 'uses' => 'Painel\HomeController@login']);

// Efetuar Login via POST
Route::post('painel/login', ['as' => 'painel.auth', 'uses' => 'Auth\AuthController@postLogin']);

// Logout do Painel
Route::get('painel/logout', ['as' => 'painel.off', 'uses' => 'Auth\AuthController@getLogout']);

Route::post('getSubcategorias', ['as' => 'get.subcategorias', function(Illuminate\Http\Request $request){

	$categoria = App\Models\PortfolioCategorias::find($request->input('cat_id'));

	if($categoria)
		return $categoria->subcategorias;
	else
		return [];
}]);


// Página principal do Painel
Route::group([
		'middleware' => 'auth',
		'namespace' => 'Painel',
		'prefix' => 'painel'
	], function () {

		Route::get('/', ['as' => 'painel.home', 'uses' => 'HomeController@index']);
		Route::post('imagens/upload', ['as' => 'imagens.upload', 'uses' => 'ImagensController@upload']);
		Route::post('imagens/uploadParalaxe', ['as' => 'imagens.upload-paralaxe', 'uses' => 'ImagensController@uploadParalaxe']);
		Route::post('idiomas/adicionar', 'PortfolioController@postAdicionarIdioma');

		Route::post('ajax/gravaOrdem', function(Illuminate\Http\Request $request){
      $itens = $request->input('data');
      $tabela = $request->input('tabela');
      for ($i = 0; $i < count($itens); $i++)
       DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
    });

		Route::resource('usuarios', 'UsuariosController', ['except' => ['show']]);

		Route::resource('about', 'AboutController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('imprensa', 'ImprensaController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('juridico', 'JuridicoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('publicacoes', 'PublicacoesController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('acaosocial', 'AcaoSocialController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('parcerias', 'ParceriasController', ['only' => ['index', 'edit', 'update']]);
		Route::resource('licenciamento', 'LicenciamentoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('contato', 'ContatoController', ['only' => ['index', 'edit', 'update']]);

		Route::resource('portfolio', 'PortfolioController', ['except' => ['show']]);

		Route::resource('idiomas', 'IdiomasController', ['except' => ['show']]);

		Route::resource('marca', 'MarcaController', ['except' => ['show']]);
    Route::resource('banners', 'BannersController', ['except' => ['show']]);
    
    Route::resource('destaques', 'DestaquesController', ['only' => ['index', 'edit', 'update']]);
	}
);


/*
Route::get('fix-83jf3453165f413q1f', function(){
	$registros = \App\Models\PortfolioParalaxe::all();
	foreach($registros as $registro){
		for ($i=1; $i <= 5; $i++) {

			$titulo = "imagem_{$i}";
			$img = $registro->{$titulo};

			$diretorios = [
				'assets/img/portfolio/paralaxe/originais/',
				'assets/img/portfolio/paralaxe/redimensionadas/horizontais/',
				'assets/img/portfolio/paralaxe/redimensionadas/verticais/',
				'assets/img/portfolio/paralaxe/thumbs/'
			];

			foreach($diretorios as $dir){
				if($img != '' && $img != '.' && $img != '..' && $img != '/' && !file_exists(public_path($dir.$img))){
					echo "-- NAO encontrado: {$dir}{$img} <br>";

					$outros_tipos = ['jpg', 'jpeg', 'bmp', 'tif', 'gif'];
					foreach($outros_tipos as $tipo){
						$novo_tipo = str_replace('png', $tipo, $img);
						if(file_exists(public_path($dir.$novo_tipo))){
							echo "mas existe {$tipo}<br>";
							//rename(public_path($dir.$novo_tipo), public_path($dir.$img));
						}
					}
					echo '<br>';
				}
			}

		}
	}
});
*/

laravel/app/Http/Controllers/Painel/AboutController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\About;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = About::all();

        return view('painel.about.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.about.edit')->with('registro', About::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = About::find($id);

        $object->texto = $request->input('texto');

        $imagem = Thumbs::make('imagem', 900, 900, 'about/');
        if($imagem) $object->imagem = $imagem;

        $object->instagram = $request->input('instagram');
        $object->twitter   = $request->input('twitter');
        $object->facebook  = $request->input('facebook');
        $object->tumblr    = $request->input('tumblr');
        $object->linkedin  = $request->input('linkedin');
        $object->pinterest = $request->input('pinterest');
        $object->youtube   = $request->input('youtube');
        $object->periscope = $request->input('periscope');
        $object->vimeo     = $request->input('vimeo');
        $object->googleplus= $request->input('googleplus');
        $object->wordpress = $request->input('wordpress');
        $object->snapchat  = $request->input('snapchat');

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.about.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/AcaoSocialController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\AcaoSocial;
use App\Models\AcaoSocialImagens;

class AcaoSocialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = AcaoSocial::all();

        return view('painel.acaosocial.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.acaosocial.edit')->with('registro', AcaoSocial::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = AcaoSocial::find($id);

        $object->texto = $request->input('texto');

        try {

            $object->save();

            $this->updateImagens($request, $id);

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.acaosocial.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

    /**
     * Update the images od the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return void
     */

    private function updateImagens(Request $request, $id)
    {
        AcaoSocialImagens::where('acao_social_id', '=', $id)->delete();

        $imagens = $request->get('imagem');

        if($imagens && is_array($imagens)){
            foreach ($imagens as $key => $value) {
                $obj = new AcaoSocialImagens;
                $obj->acao_social_id = $id;
                $obj->imagem = $value;
                $obj->ordem = $key;
                $obj->save();
            }
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Libs\Thumbs;

class BannersController extends Controller
{

  protected $pathImagens = 'banners/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Banner::ordenado()->get();

      return view('painel.banners.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.banners.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
      	'imagem' => 'required|image'
    	]);

      $object = new Banner;

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.banners.edit')->with('registro', Banner::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'imagem' => 'sometimes|image'
    	]);

      $object = Banner::find($id);

      $object->titulo = $request->titulo;
      $object->frase = $request->frase;
      $object->link = $request->link;

      $imagem = Thumbs::make('imagem', null, 220, $this->pathImagens);
      if($imagem) $object->imagem = $imagem;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.banners.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Banner::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.banners.index');
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\Contato;

class ContatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = Contato::all();

        return view('painel.contato.index')->with(compact('registros'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.contato.edit')->with('registro', Contato::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = Contato::find($id);

        $object->fill($request->except('_method', '_token'));

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.contato.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use View;

class HomeController extends Controller {

    public function index()
	{
		return View::make('painel.home.index');
	}

	public function login()
	{
		return View::make('painel.login.index');
	}

}

laravel/app/Http/Controllers/Painel/ImprensaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use View;

use App\Libs\Thumbs;
use App\Models\Imprensa;

class ImprensaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $registros = Imprensa::all();

        return view('painel.imprensa.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return view('painel.imprensa.edit')->with('registro', Imprensa::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $object = Imprensa::find($id);

        $object->texto = $request->input('texto');

        $imagem = Thumbs::make('imagem', 900, 900, 'imprensa/');
        if($imagem) $object->imagem = $imagem;

        try {

            $object->save();

            $request->session()->flash('sucesso', 'Texto alterado com sucesso.');

            return redirect()->route('painel.imprensa.index');

        } catch (\Exception $e) {

            $request->flash();

            return back()->withErrors(array('Erro ao alterar texto! ('.$e->getMessage().')'));

        }
    }

}

laravel/resources/views/painel/template/imagens-upload.blade.php
<hr>

<div class="well">

	<label>Imagens</label>

	<div class="multiUpload">
		<div class="icone">
			<span class="glyphicon glyphicon-open"></span>
			<span class="glyphicon glyphicon-refresh"></span>
		</div>
		<p>
			Escolha as imagens da Página. Você pode selecionar mais de um arquivo ao mesmo tempo. Você também pode arrastar e soltar arquivos nesta área para começar a enviar.<br>
			Se preferir também pode utilizar o botão abaixo para selecioná-las.
		</p>
		<input id="fileupload-geral" class="fileupload" type="file" name="files" data-url="painel/imagens/upload" data-path="{{ $path }}" data-fieldname='imagem' data-limite="0" data-fieldname='imagem' multiple>

	</div>

	<div class="limiteImagensAtingido" style='display:none;'>
		<div class="panel panel-default">
			<div class="panel-body bg-info">
		    	Número máximo de imagens (16) atingido nesta página.
		  	</div>
		</div>
	</div>

	<div class="listaImagens">
		@if(sizeof($registro->imagens))
			@foreach($registro->imagens as $k => $v)
				<div class='projetoImagem'>
		        	<img src="assets/img/{{ $path }}/thumbs/{{ $v->imagem }}">
		        	<input type='hidden' name='imagem[]' value="{{$v->imagem}}">
		        	<a href='#' class='btn btn-sm btn-danger btn-remover' title='remover a imagem'><span class='glyphicon glyphicon-remove-sign'></span> <strong>remover imagem</strong></a>
	        	</div>
			@endforeach
		@endif
	</div>

	@if (!isset($hide_ordering) || !$hide_ordering)
		<div class="panel panel-default">
			<div class="panel-body">
				Você pode clicar e arrastar as imagens para ordená-las.
			</div>
		</div>
	@endif
</div>

<hr>

laravel/resources/views/painel/template/index.blade.php
<!DOCTYPE html>
<html lang="pt-BR" class="no-js">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="robots" content="index, nofollow" />
    <meta name="author" content="Trupe Design" />
    <meta name="copyright" content="2013 Trupe Design" />
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <title>{{ config('site.titulo') }} - Painel Administrativo</title>

	<base href="{{ url() }}/">
	<script>var BASE = "{{ url() }}"</script>

	<link rel="stylesheet" href="assets/css/painel.css">

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="assets/vendor/jquery/dist/jquery.min.js"><\/script>')</script>

	<script src='assets/js/modernizr.js'></script>

</head>
	<body class="body-painel">

		@include('painel.template.menu')

		@yield('conteudo')

		<footer>
			<div class="container-fluid">
				<a href="http://www.trupe.net" target="_blank" title="Criação de Sites : Trupe Agência Criativa">© Criação de Sites : Trupe Agência Criativa</a>
			</div>
		</footer>

		<script src='assets/js/ckeditor/ckeditor.js'></script>
		<script src='assets/js/ckeditor/adapters/jquery.js'></script>
		<script src='assets/js/painel.js?nocache={{ time() }}'></script>

	</body>
</html>

laravel/resources/views/painel/template/mensagens.blade.php
@if($errors->any())
	<div class="alert alert-block alert-danger">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ $errors->first() }}
	</div>
@endif

@if(Session::has('sucesso'))
	<div class="alert alert-block alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ Session::get('sucesso') }}
	</div>
@endif

laravel/resources/views/painel/template/menu.blade.php
<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-painel" aria-expanded="false">
			    <span class="sr-only">Navegação</span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
			    <span class="icon-bar"></span>
		    </button>
		    <a class="navbar-brand" title="Página Inicial" href="{{ URL::route('painel.home') }}">{{ config('site.titulo') }}</a>
		</div>

		<div class="collapse navbar-collapse" id="menu-painel">
			<ul class="nav navbar-nav">

				<li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.home')}}" title="Início">Início</a>
				</li>

				<li class="dropdown @if(preg_match('~painel.(marca|banners*)~', Route::currentRouteName())) active @endif ">

					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home <b class="caret"></b></a>

					<ul class="dropdown-menu">
						<li @if(preg_match('~painel.(marca*)~', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.marca.index')}}" title="Marca">Marca</a>
						</li>
						<li @if(preg_match('~painel.(banners*)~', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.banners.index')}}" title="Banners">Banners</a>
						</li>
					</ul>
				</li>

				<li @if(str_is('painel.about*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.about.index')}}" title="About">About</a>
				</li>

        <li @if(str_is('painel.destaques*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.destaques.index')}}" title="Destaques">Destaques</a>
				</li>

				<li @if(str_is('painel.imprensa*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.imprensa.index')}}" title="Imprensa">Imprensa</a>
				</li>

				<li @if(str_is('painel.publicacoes*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.publicacoes.index')}}" title="Publicações">Publicações</a>
				</li>

				<li @if(str_is('painel.acaosocial*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.acaosocial.index')}}" title="Ação Social">Ação Social</a>
				</li>

				<li @if(str_is('painel.juridico*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.juridico.index')}}" title="Jurídico">Jurídico</a>
				</li>

				<li @if(str_is('painel.parcerias*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.parcerias.index')}}" title="Parcerias">Parcerias</a>
				</li>

				<li @if(str_is('painel.licenciamento*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.licenciamento.index')}}" title="Licenciamento">Licenciamento</a>
				</li>

				<li @if(str_is('painel.contato*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.contato.index')}}" title="Contato">Contato</a>
				</li>

				<li @if(str_is('painel.portfolio*', Route::currentRouteName())) class="active" @endif>
					<a href="{{URL::route('painel.portfolio.index')}}" title="Portfolio">Portfolio</a>
				</li>

				<li class="dropdown @if(preg_match('~painel.(usuarios|idiomas*)~', Route::currentRouteName())) active @endif ">

					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sistema <b class="caret"></b></a>

					<ul class="dropdown-menu">
						<li @if(preg_match('~painel.(usuarios*)~', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.usuarios.index')}}" title="Usuários do Painel">Usuários</a>
						</li>
						<li @if(preg_match('~painel.(idiomas*)~', Route::currentRouteName())) class="active" @endif >
							<a href="{{URL::route('painel.idiomas.index')}}" title="Gerenciar Idiomas">Gerenciar Idiomas</a>
						</li>
						<li role="separator" class="divider"></li>
						<li>
							<a href="{{URL::route('painel.off')}}" title="Logout">Logout</a>
						</li>
					</ul>
				</li>

			</ul>
		</div>

	</div>
</nav>